/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155URIStorage } from "src/typechain-types/@openzeppelin/contracts/token/ERC1155/extensions/ERC1155URIStorage";
export type { IERC1155MetadataURI } from "src/typechain-types/@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI";
