/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721URIStorage } from "src/typechain-types/@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage";
export type { IERC721Metadata } from "src/typechain-types/@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata";
