/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155 from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155";
export * as erc721 from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC721";
