/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Ownable__factory } from "src/typechain-types/factories/@openzeppelin/contracts/access/Ownable__factory";
