/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "src/typechain-types/contracts/interfaces";
export type { interfaces };
export type { Erc1155 } from "src/typechain-types/contracts/Erc1155";
export type { Erc721 } from "src/typechain-types/contracts/Erc721";
export type { Erc721Factory } from "src/typechain-types/contracts/Erc721Factory";
export type { Lock } from "src/typechain-types/contracts/Lock";
export type { Robot } from "src/typechain-types/contracts/Robot";
