/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IErc1155__factory } from "./IErc1155__factory";
export { IErc721__factory } from "./IErc721__factory";
