/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IErc1155__factory } from "src/typechain-types/factories/contracts/interfaces/IErc1155__factory";
export { IErc721__factory } from "src/typechain-types/factories/contracts/interfaces/IErc721__factory";
