/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165 } from "src/typechain-types/@openzeppelin/contracts/utils/introspection/ERC165";
export type { IERC165 } from "src/typechain-types/@openzeppelin/contracts/utils/introspection/IERC165";
