/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as introspection from "src/typechain-types/@openzeppelin/contracts/utils/introspection";
export type { introspection };
