/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155 from "src/typechain-types/@openzeppelin/contracts/token/ERC1155";
export type { erc1155 };
import type * as erc721 from "src/typechain-types/@openzeppelin/contracts/token/ERC721";
export type { erc721 };
