/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155/extensions";
export { ERC1155__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155/ERC1155__factory";
export { IERC1155__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155/IERC1155__factory";
export { IERC1155Receiver__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155/IERC1155Receiver__factory";
