/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "src/typechain-types/@openzeppelin/contracts/token/ERC721/extensions";
export type { extensions };
export type { ERC721 } from "src/typechain-types/@openzeppelin/contracts/token/ERC721/ERC721";
export type { IERC721 } from "src/typechain-types/@openzeppelin/contracts/token/ERC721/IERC721";
export type { IERC721Receiver } from "src/typechain-types/@openzeppelin/contracts/token/ERC721/IERC721Receiver";
