/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface Erc721FactoryInterface extends utils.Interface {
  functions: {
    "allErc721(uint256)": FunctionFragment;
    "allErc721Length()": FunctionFragment;
    "countMap(address)": FunctionFragment;
    "createErc721(string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allErc721"
      | "allErc721Length"
      | "countMap"
      | "createErc721"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allErc721",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "allErc721Length",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "countMap",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createErc721",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "allErc721", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allErc721Length",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "countMap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createErc721",
    data: BytesLike
  ): Result;

  events: {
    "Erc721Created(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Erc721Created"): EventFragment;
}

export interface Erc721CreatedEventObject {
  erc721: string;
  arg1: BigNumber;
}
export type Erc721CreatedEvent = TypedEvent<
  [string, BigNumber],
  Erc721CreatedEventObject
>;

export type Erc721CreatedEventFilter = TypedEventFilter<Erc721CreatedEvent>;

export interface Erc721Factory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Erc721FactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allErc721(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    allErc721Length(overrides?: CallOverrides): Promise<[BigNumber]>;

    countMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createErc721(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  allErc721(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  allErc721Length(overrides?: CallOverrides): Promise<BigNumber>;

  countMap(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createErc721(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allErc721(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    allErc721Length(overrides?: CallOverrides): Promise<BigNumber>;

    countMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createErc721(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "Erc721Created(address,uint256)"(
      erc721?: null,
      arg1?: null
    ): Erc721CreatedEventFilter;
    Erc721Created(erc721?: null, arg1?: null): Erc721CreatedEventFilter;
  };

  estimateGas: {
    allErc721(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allErc721Length(overrides?: CallOverrides): Promise<BigNumber>;

    countMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createErc721(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allErc721(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allErc721Length(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    countMap(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createErc721(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
