/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface RobotInterface extends utils.Interface {
  functions: {
    "batchAll(address[],uint256[],string[],string[],address[],address[],uint256[],uint256[],string[],string[],uint256[])": FunctionFragment;
    "batchLockt1155(address,address[],uint256[],string[],string[],uint256[])": FunctionFragment;
    "batchMint721(address,address[],string[],string[])": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchAll"
      | "batchLockt1155"
      | "batchMint721"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchAll",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchLockt1155",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMint721",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "batchAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchLockt1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchMint721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "Buy(address,uint256,uint256,address,address,uint256,uint256)": EventFragment;
    "Lock(address,string,string,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Lock"): EventFragment;
}

export interface BuyEventObject {
  contractAddress: string;
  cType: BigNumber;
  tokenId: BigNumber;
  from: string;
  to: string;
  amount: BigNumber;
  price: BigNumber;
}
export type BuyEvent = TypedEvent<
  [string, BigNumber, BigNumber, string, string, BigNumber, BigNumber],
  BuyEventObject
>;

export type BuyEventFilter = TypedEventFilter<BuyEvent>;

export interface LockEventObject {
  contractAddress: string;
  name: string;
  tokenURI: string;
  to: string;
  tokenId: BigNumber;
  amount: BigNumber;
}
export type LockEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber],
  LockEventObject
>;

export type LockEventFilter = TypedEventFilter<LockEvent>;

export interface Robot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RobotInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchAll(
      addresses: PromiseOrValue<string>[],
      types: PromiseOrValue<BigNumberish>[],
      orderIds: PromiseOrValue<string>[],
      orderHashs: PromiseOrValue<string>[],
      froms: PromiseOrValue<string>[],
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      tokenURIs: PromiseOrValue<string>[],
      names: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchLockt1155(
      erc1155: PromiseOrValue<string>,
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      names: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchMint721(
      erc721: PromiseOrValue<string>,
      accounts: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      collectionIds: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  batchAll(
    addresses: PromiseOrValue<string>[],
    types: PromiseOrValue<BigNumberish>[],
    orderIds: PromiseOrValue<string>[],
    orderHashs: PromiseOrValue<string>[],
    froms: PromiseOrValue<string>[],
    tos: PromiseOrValue<string>[],
    tokenIds: PromiseOrValue<BigNumberish>[],
    amounts: PromiseOrValue<BigNumberish>[],
    tokenURIs: PromiseOrValue<string>[],
    names: PromiseOrValue<string>[],
    values: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchLockt1155(
    erc1155: PromiseOrValue<string>,
    tos: PromiseOrValue<string>[],
    tokenIds: PromiseOrValue<BigNumberish>[],
    names: PromiseOrValue<string>[],
    tokenURIs: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchMint721(
    erc721: PromiseOrValue<string>,
    accounts: PromiseOrValue<string>[],
    tokenURIs: PromiseOrValue<string>[],
    collectionIds: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    batchAll(
      addresses: PromiseOrValue<string>[],
      types: PromiseOrValue<BigNumberish>[],
      orderIds: PromiseOrValue<string>[],
      orderHashs: PromiseOrValue<string>[],
      froms: PromiseOrValue<string>[],
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      tokenURIs: PromiseOrValue<string>[],
      names: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchLockt1155(
      erc1155: PromiseOrValue<string>,
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      names: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchMint721(
      erc721: PromiseOrValue<string>,
      accounts: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      collectionIds: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Buy(address,uint256,uint256,address,address,uint256,uint256)"(
      contractAddress?: PromiseOrValue<string> | null,
      cType?: PromiseOrValue<BigNumberish> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      from?: null,
      to?: null,
      amount?: null,
      price?: null
    ): BuyEventFilter;
    Buy(
      contractAddress?: PromiseOrValue<string> | null,
      cType?: PromiseOrValue<BigNumberish> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      from?: null,
      to?: null,
      amount?: null,
      price?: null
    ): BuyEventFilter;

    "Lock(address,string,string,address,uint256,uint256)"(
      contractAddress?: PromiseOrValue<string> | null,
      name?: PromiseOrValue<string> | null,
      tokenURI?: PromiseOrValue<string> | null,
      to?: null,
      tokenId?: null,
      amount?: null
    ): LockEventFilter;
    Lock(
      contractAddress?: PromiseOrValue<string> | null,
      name?: PromiseOrValue<string> | null,
      tokenURI?: PromiseOrValue<string> | null,
      to?: null,
      tokenId?: null,
      amount?: null
    ): LockEventFilter;
  };

  estimateGas: {
    batchAll(
      addresses: PromiseOrValue<string>[],
      types: PromiseOrValue<BigNumberish>[],
      orderIds: PromiseOrValue<string>[],
      orderHashs: PromiseOrValue<string>[],
      froms: PromiseOrValue<string>[],
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      tokenURIs: PromiseOrValue<string>[],
      names: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchLockt1155(
      erc1155: PromiseOrValue<string>,
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      names: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchMint721(
      erc721: PromiseOrValue<string>,
      accounts: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      collectionIds: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    batchAll(
      addresses: PromiseOrValue<string>[],
      types: PromiseOrValue<BigNumberish>[],
      orderIds: PromiseOrValue<string>[],
      orderHashs: PromiseOrValue<string>[],
      froms: PromiseOrValue<string>[],
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      tokenURIs: PromiseOrValue<string>[],
      names: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchLockt1155(
      erc1155: PromiseOrValue<string>,
      tos: PromiseOrValue<string>[],
      tokenIds: PromiseOrValue<BigNumberish>[],
      names: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchMint721(
      erc721: PromiseOrValue<string>,
      accounts: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      collectionIds: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
