/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721URIStorage__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage__factory";
export { IERC721Metadata__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata__factory";
