/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155URIStorage__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155/extensions/ERC1155URIStorage__factory";
export { IERC1155MetadataURI__factory } from "src/typechain-types/factories/@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI__factory";
