/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "src/typechain-types/@openzeppelin/contracts/access";
export type { access };
import type * as token from "src/typechain-types/@openzeppelin/contracts/token";
export type { token };
import type * as utils from "src/typechain-types/@openzeppelin/contracts/utils";
export type { utils };
