/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "src/typechain-types/@openzeppelin/contracts/token/ERC1155/extensions";
export type { extensions };
export type { ERC1155 } from "src/typechain-types/@openzeppelin/contracts/token/ERC1155/ERC1155";
export type { IERC1155 } from "src/typechain-types/@openzeppelin/contracts/token/ERC1155/IERC1155";
export type { IERC1155Receiver } from "src/typechain-types/@openzeppelin/contracts/token/ERC1155/IERC1155Receiver";
