/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IErc1155 } from "src/typechain-types/contracts/interfaces/IErc1155";
export type { IErc721 } from "src/typechain-types/contracts/interfaces/IErc721";
