/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC165__factory } from "src/typechain-types/factories/@openzeppelin/contracts/utils/introspection/ERC165__factory";
export { IERC165__factory } from "src/typechain-types/factories/@openzeppelin/contracts/utils/introspection/IERC165__factory";
